### ISSUE TITLE
Add support for inline frame content

### ISSUE THREAD

**Issue by garci66** [concerto/concerto-iframe#21]
It would be great to support inline frame content where the URL actually specifies the content. #20 Adds this support by allowing the user to specify an data/text-html source instead of an "external" url with protocol handler. 

This would also require the "data" field of the contents to be expanded to something larger (currently its limitted at 64K), ideally a 16M restriciton (equivalent to MEDIUMTEXT in MYSQL) would be great.

**Comment by mfrederickson** [comment]
I'm going to close this since the content is now supported via #20 and there is a separate ticket to track the data field expansion.
